---
ansible_user: ops
ansible_python_interpreter: "/home/{{ ansible_user }}/ansible_venv/bin/python"

api_service: "api-service"
juritj_private_name: "juritj.judilibre-prive.local"

s3_url: "http://bucket-service.bucket.svc.cluster.local:9000"
s3_region: "eu-west-paris-1"
s3_bucket_name: "juritj-bucket"
no_color: "true"
