name: juritj

services:
  bucket:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    command: minio server /data --console-address :9001
    volumes:
      - bucket-storage:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root1234
    networks:
      - judilibre-local

  createbuckets:
    image: minio/mc
    depends_on:
      - bucket
    entrypoint: > # source: https://github.com/minio/minio/issues/4769 
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://bucket:9000 root root1234;
      /usr/bin/mc mb --ignore-existing myminio/juritj-test-bucket &&
      /usr/bin/mc mb --ignore-existing myminio/juritj-test-bucket-normalized &&
      /usr/bin/mc policy download myminio/juritj-test-bucket &&
      /usr/bin/mc policy download myminio/juritj-test-bucket-normalized &&
      /usr/bin/mc admin user svcacct add --access-key "local_access_key" --secret-key "local_secret_key" myminio root;
      exit 0;
      "
    networks:
      - judilibre-local

  api:
    build:
      context: ./
      target: api-local
    env_file:
      - docker.env
    ports:
      - 3009:3009
    volumes:
      - .:/home/node
    networks:
      - judilibre-local

  batch: 
    build:
      context: ./
      target: batch-local
    env_file:
      - docker.env
    volumes:
      - .:/home/node
    networks:
      - judilibre-local

networks:
  judilibre-local:
    external: true

volumes:
  bucket-storage:
    driver: local
    name: juritj-bucket-storage
