version: "3.7"

services:
  db:
    image: mongo:4.4
    command: mongod --port 55431
    volumes:
      - mongo-storage:/data/db
    expose:
      - 55431
    ports:
      - 55431:55431

  bucket:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    command: minio server /data --console-address :9001
    volumes:
      - bucket-storage:/data
    expose: 
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root1234

  createbuckets:
    image: minio/mc
    depends_on:
      - bucket
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://bucket:9000 root root1234;
      /usr/bin/mc rm -r --force myminio/juritj-test-bucket;
      /usr/bin/mc mb myminio/juritj-test-bucket;
      /usr/bin/mc policy download myminio/juritj-test-bucket;
      /usr/bin/mc rm -r --force myminio/juritj-test-bucket-normalized;
      /usr/bin/mc mb myminio/juritj-test-bucket-normalized;
      /usr/bin/mc policy download myminio/juritj-test-bucket-normalized;
      /usr/bin/mc admin user svcacct add --access-key "local_access_key" --secret-key "local_secret_key" myminio root;
      exit 0;
      "

  api:
    build:
      context: ./
      target: api
    environment: 
      - DOC_LOGIN=root
      - DOC_PASSWORD=root
      - S3_ACCESS_KEY=local_access_key
      - S3_SECRET_KEY=local_secret_key
      - S3_URL=http://bucket:9000 
      - S3_REGION=eu-west-paris-1
      - S3_BUCKET_NAME_RAW=juritj-test-bucket
      - S3_BUCKET_NAME_NORMALIZED=juritj-test-bucket-normalized
      - SERVER_KEY=./secrets/dev/server-key.pem
      - SERVER_CERT=./secrets/dev/server-cert.pem
      - SERVER_CA_CERT=./secrets/dev/ca-cert.pem
      - WINCI_CA_CERT=./secrets/dev/winci-ca-cert.pem
    expose: 
      - 3009
    ports:
      - 3009:3000

  batch: 
    build:
      context: ./
      target: batch
    environment:
      - S3_ACCESS_KEY=local_access_key
      - S3_SECRET_KEY=local_secret_key
      - S3_URL=http://bucket:9000 
      - S3_REGION=eu-west-paris-1
      - S3_BUCKET_NAME_RAW=juritj-test-bucket
      - S3_BUCKET_NAME_NORMALIZED=juritj-test-bucket-normalized
      - MONGODB_URL=mongodb://db:55431/
      - SERVER_KEY=./secrets/dev/server-key.pem
      - SERVER_CERT=./secrets/dev/server-cert.pem
      - SERVER_CA_CERT=./secrets/dev/ca-cert.pem

networks:
  default:
    name: juritj-network

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
  bucket-storage:
    driver: local
    name: juritj-bucket-storage


