---
- name: Deploy namespace
  import_tasks: namespace.yml

- name: Deploy configmap
  import_tasks: configmap.yml

- name: Deploy secrets
  import_tasks: secrets.yml

- name: Deploy deployment
  import_tasks: deployment.yml

- name: Deploy services
  import_tasks: service.yml

- name: Deploy ingresses
  import_tasks: ingress.yml
