---
- name: Deploy namespace
  import_tasks: namespace.yml

- name: Deploy configmap
  include_tasks: '{{item}}'
  loop: "{{ lookup('fileglob'  'configmap/*.yml' ) }}"

- name: Deploy secrets
  include_tasks: '{{item}}'
  loop: "{{ lookup('fileglob'  'secret/*.yml' ) }}"

- name: Deploy deployments
  include_tasks: '{{item}}'
  loop: "{{ lookup('fileglob'  'deployment/*.yml' ) }}"

- name: Deploy services
  include_tasks: '{{item}}'
  loop: "{{ lookup('fileglob'  'service/*.yml' ) }}"

- name: Deploy ingress
  import_tasks: ingress.yml
