---
- name: Creation secrets s3
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: s3-secret
        namespace: "{{ juritj_namespace }}"
        labels:
          app: "{{ juritj_application }}"
      type: Opaque
      data:
        S3_ACCESS_KEY: "{{ s3_access_key | b64encode }}"
        S3_SECRET_KEY: "{{ s3_secret_key | b64encode }}"

...
