apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket-deployment
  namespace: juritj
  labels:
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bucket
  template:
    metadata:
      labels:
        app: bucket
    spec:
      containers:
        - name: bucket
          image: minio/minio:RELEASE.2023-02-27T18-10-45Z
          ports:
          - containerPort: 9000
          - containerPort: 9001
          env:
          - name: MINIO_ROOT_USER
            value: $MINIO_USER
          - name: MINIO_ROOT_PASSWORD
            value: $MINIO_PASSWORD
          - name: MINIO_BROWSER_REDIRECT_URL
            value: "https://juritj.judilibre-prive.local/bucket"
          volumeMounts:
          - name: bucket-volume
            mountPath: /data
          command:
          - minio
          args:
          - server
          - /data
          - --console-address 
          - ":9001"
      volumes:
      - name: bucket-volume
        hostPath:
          path: /data/bucket

---
apiVersion: v1
kind: Service
metadata:
  name: bucket-service
  namespace: juritj
spec:
  selector:
    app: bucket
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  type: ClusterIP