---
- name: Creation api service
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ api_service }}"
        namespace: "{{ juritj_namespace }}"
      spec:
        selector:
          app: "{{ api_app_id }}"
        ports:
          - name: api
            port: 3000
            targetPort: 3000
        type: ClusterIP

...
